[package]
name = "zinc64"
version = "0.1.0"
authors = ["Sebastian Jastrzebski <sebby2k@gmail.com>"]
repository = "https://github.com/digitalstreamio/zinc64"
categories = ["c64", "emulator"]
keywords = ["c64", "commodore", "emulator"]
readme = "README.md"
description = "Commodore 64 rustified"

[dependencies]
bit_field = "0.9"
byteorder = "1.2"
getopts = "0.2"
gl = "0.7"
log = "0.3"
resid-rs = "0.4"
sdl2 = "0.31"
time = "0.1"
