[package]
name = "zinc64"
version = "0.1.0"
authors = ["Sebastian Jastrzebski <sebby2k@gmail.com>"]
license = "GPL-2.0+"
readme = "README.md"
keywords = ["c64", "commodore", "emulator"]
repository = "https://github.com/digitalstreamio/zinc64"
homepage = "https://github.com/digitalstreamio/zinc64"
categories = ["c64", "emulator"]
description = """
Commodore 64 emulator toolkit with batteries included but swappable
"""
exclude = [
    "bin/*",
    "doc/*",
    "res/*",
]

[dependencies]
bit_field = "0.9"
byteorder = "1.2"
getopts = "0.2"
gl = "0.7"
log = "0.3"
resid-rs = "0.5"
time = "0.1"

[dependencies.sdl2]
version = "0.31"
default-features = false
features = ["unsafe_textures"]
